version: 0.2

phases:
  install:
    commands:
      - npm install -g pm2
      - npm install

  build:
    commands:
      - echo Build done

  post_build:
    commands:
      - pm2 stop all || true
      - pm2 start app.js
