version: 0.2

phases:
  install:
    commands:
      - echo Installing...
  
  build:
    commands:
      - echo Build phase

  post_build:
    commands:
      - echo Deploying to EC2
      - ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@3.110.220.138 "
          cd /home/ubuntu/node-app &&
          git pull &&
          npm install &&
          pm2 delete all || true &&
          pm2 start app.js
        "
